### PR TITLE
Issue420

### PR DESCRIPTION
**Pull request by vibhuti019**
Move supporters to a new panel #424

### CODE REVIEW

**Comment by rabbah** [comment]
Screen Shot 2020-02-26 at 10 31 15 PM

**Comment by rabbah** [comment]
x

**Comment by vibhuti019** [comment]
I have filed the cla.

**Comment by rabbah** [comment]
Thanks @vibhuti019 - I see you listed in the apache roster now.

**Comment by rabbah** [comment]
@vibhuti019 do you have a twitter account?

**Comment by vibhuti019** [comment]
@rabbah I am not active on twitter. Do you have insta account ??

**Comment by mrutkows** [comment]
@vibhuti019 Thanks for your work on the Supporters section; really like the new layout!

**Comment by mrutkows** [comment]
Closes https://github.com/apache/openwhisk-website/issues/420

**Pull request merged**
