### PR TITLE
Move supporters to a new panel

### PR DESCRIPTION
**Pull request by vibhuti019**
Issue #420

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks @vibhuti019 this looks great.
Screen Shot 2020-02-20 at 7 28 44 PM

What do you think about making the supporter panel wider so the logos can be bigger?  Or reducing the gap between logos.

Also have you filed an Apache CLA see https://github.com/apache/openwhisk-website/blob/master/CONTRIBUTING.md if not.

**Comment by vibhuti019** [comment]
@rabbah for mobile view it will be just same as it was coming before this update.
 Or if you ask I can disable it.

**Comment by rabbah** [comment]
I am building the website from your PR. The screenshot above is with your change. In my previous comment, I was asking if the new column with the logos could be made wider to allow the logos to be a little larger. 

I checked the site on mobile - looks like the supporter div is misaligned. 

Screen Shot 2020-02-21 at 1 21 24 PM

**Comment by vibhuti019** [comment]
Okay I'll correct it.. 
Thank you for guiding for the same.

**Comment by vibhuti019** [comment]
I have made the required changes.

**Comment by rabbah** [comment]
Replaced by https://github.com/apache/openwhisk-website/pull/427.

**Pull request closed without merging**
