### PR TITLE
update community supporters

### PR DESCRIPTION
**Pull request by buggtb**

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks @buggtb - this is exciting.

**Comment by mrutkows** [comment]
@rabbah the asf-site branch did not pick up this change... and would love very much to see this logo as a huge fan of JPL...

**Comment by dgrove-oss** [comment]
The Jenkins job to build the website is broken yet again with the recurring `npm not found` problem.

https://builds.apache.org/view/O/view/OpenWhisk/job/OpenWhisk-website/308/console

A problem with the ASF insfrastructure, not ours.

**Comment by rabbah** [comment]
Reported as https://issues.apache.org/jira/browse/INFRA-19843.

**Pull request merged**
